name: 'Release @neo4j-devtools/arc'

defaults:
  run:
    working-directory: src/neo4j-arc

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v2
        with:
          repository: neo4j/neo4j-browser
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@neo4j-devtools'
      - run: npm -g install yarn
      # - run: yarn test
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: 'src/neo4j-arc/package.json'
          access: 'public'
